title: The Francis Garikayi Blogs
description: > # this means to ignore newlines until "baseurl:"
  This blog is about Politics, Education and Economics in Southern Africa
  My main focus is on the last three countries to gain independece-that is 
  Namibia, South Africa and Zimbabwe. I will share my experiences from being 
  a citizen of Zimbabwe and having worked in Namibia and educated in South Africa
  A common theme across the three countries is that, firstly they all faced some
  form of racial segreggation and or aparheid. Secondly and since the dawm of
  majority rule in all the lands, instances of large scale corruption in the 
  countries have dominated global headlines. Finally, the three nations seem to 
  grapple with widespread power shortages and poor service delivery. 
permalink: #':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #veegarikayi

# Author Settings
author: francis vee garikayi # add your name
author-img: francis-garikayi.jpg # add your photo
about-author: I am a PhD Researcher whose interests are in Politics, Economics
              and Education in Southern Africa. My main focus is on Zimbabwe and
              South Africa. # add description
social-twitter: veegarikayi
social-facebook: # add your Facebook handle
social-github: valentinegarikayi # add your Github handle
social-linkedin: www.linkedin.com/in/francis-valentine-garikayi # add your Linkedin handle
social-email: fran.garikayi@gmail.com # add your Email address

# Disqus
discus-identifier: Schrodinger's-Cat # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
